# Site settings
title: CMSC423 (Fall 2015)
email: hcorrada@umiacs.umd.edu
description: "CMSC423, Bioinformatics. University of Maryland, College Park. Department of Computer Science"
baseurl: "/~hcorrada/CMSC423"
url: "http://cbcb.umd.edu/~hcorrada/CMSC423"
twitter_username: hcorrada
github_username:  hcorrada

pageOrder: ["/index.html", "/logistics.html", "/projects.html", "/resources.html", "/syllabus.html"]

# Build settings
markdown: kramdown
highlighter: pygments
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

# my variables
book_url: http://bioinformaticsalgorithms.com/
book_videos_url: https://www.youtube.com/user/bioinfalgorithms/playlists
piazza_url: https://piazza.com/class/ie0cq312nd251
elms_url: https://myelms.umd.edu/courses/1152063
rosalind_prelecture_url: http://rosalind.info/classes/232/
rosalind_final_url: http://rosalind.info/classes/233/
